apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: adidas-deployment
spec:
  selector:
    matchLabels:
      app: adidas
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: adidas
    spec:
      containers:
      - name: adidas
        image: adidas-observer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: GOOGLE_MAPS_API_KEY
          value: "<GOOGLE_MAPS_API_KEY VALUE>"
        - name: NASA_API_KEY
          value: "<NASA_API_KEY VALUE>"
